### ISSUE TITLE
epub/mobi of new rust book

### ISSUE THREAD

**Issue by svraghavan** [mkaito/rustdocs_ebook#1]
Is it possible to alter the script to add epub/mobi generation of the rust book. Thanks in advance.

**Comment by mkaito** [comment]
I've poked @steveklabnik about making an official epub/mobi version of it, and he said he'd look into it. 

The script that populates this repository already grabs any epubs, converts them to mobi, and pushes the whole thing. That is, the current build system just doesn't build an epub for the book, and that's not something I can do much about.

**Comment by steveklabnik** [comment]
yah, we want to do this officially for sure

**Comment by mkaito** [comment]
Thanks Steve! Looking forward to it.

**Comment by svraghavan** [comment]
Thanks Chris.

On Friday, March 13, 2015, Chris Hoppner notifications@github.com wrote:

> Thanks Steve! Looking forward to it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkaito/rustdocs_ebook/issues/1#issuecomment-79734662.

## 

Sent from Gmail Mobile
